### ISSUE TITLE
issue when authenticated to https://localhost:8080

### ISSUE THREAD

**Issue by Alexc0007** [sensu/sensu-go-ansible#126]
**Bug description**
our sensu api server is configured to work on https://localhost:8080
when i try to use sensu-go-ansible, it cant verify the client certificate and throws the following error:
```
Executing playbook basic_checks.yml

- us-west-2 on hosts: us-west-2 -
Gathering Facts...
  MY_HOST_IP ok
cpu_load...
  MY_HOST_IP failed: {
    "changed": false, 
    "msg": "GET request failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)"
}
```

**How to reproduce the bug**
1. configure sensu backend to use https on api:
```
---
#
# Ansible managed
#
api-url: https://localhost:8080
cert-file: /etc/ssl/certs/server/Server.pem
key-file: /etc/ssl/certs/server/Server-key.pem
state-dir: /var/lib/sensu/sensu-backend
trusted-ca-file: /etc/ssl/certs/ca/ca.pem
log-level: error
```
2. use the ansible collection to manage sensu 

**Expected result**
i expect to have the ability to provide a path to the certificate that will be used during the api call to sensu
and have the ability to disable certificate validation as part of the 'auth' util.

**Actual result**
now i dont have any control over ssl authentication

**Component versions**
 - Ansible Version: 2.9.1
 - Sensu Go Collection Version 1.0.0
 - Sensu Go Backend Version:  5.14.1

**Additional context**

i would expect a yaml file to look this way:
where u have the ability to turn off certificate validation on the auth section
and have the ability to pass client cert.
```
tasks:
    - name: cpu_load
      check:
        auth:
          url: https://localhost:8080
          password: '{{ sensu_password }}'
          validate_certs: False
          #client_cert: PATH_TO_CLIENT_CERT
        state: present
        timeout: 10
        namespace: default
        subscriptions: all
        output_metric_handlers: ["influx-db"]
        output_metric_format: nagios_perfdata
        name: cpu_load
        command: check_load -w 15,10,5 -c 30,25,20
        interval: 180
      vars:
        sensu_password: PASSWORD
```
to achieve that, the options 'validate_certs' and 'client_cert' should be passed to to 'request' method in file: sensu_go/plugins/module_utils/http.py
and later on the open_url method
for example:
```
raw_resp = open_url(
            method=method,validate_certs=False, url=url, data=data, headers=headers, **kwargs
        )
```

**Comment by tadeboro** [comment]
@Alexc0007 We just merged a PR #204 that allows playbook authors to disable the certificate verification completely or to use a custom CA bundle for verification.

You can now connect to the backend that uses a self-signed certificate in one of the following ways:

```
- name: List assets without validating certificate at all
  sensu.sensu_go.asset_info:
    auth:
      url: https://backend.address:8080
      verify: false
```

```
- name: List assets using custom CA bundle for cert verification
  sensu.sensu_go.asset_info:
    auth:
      url: https://backend.address:8080
      ca_path: /path/to/ca.bundle
```

Happy automating!
