### ISSUE TITLE
manage assets isnt working as expected

### ISSUE THREAD

**Issue by Alexc0007** [sensu/sensu-go-ansible#129]
**Bug description**
when using sensu-go-ansible to manage assets it creates invalid assests

this is an asset created by sensu-go-ansible:
```
manage influxdb asset...

  172.18.159.51 ok: {
    "changed": false, 
    "object": {
        "builds": [
            {
                "filters": null, 
                "headers": null, 
                "sha512": "612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd", 
                "url": "https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz"
            }
        ], 
        "filters": null, 
        "headers": null, 
        "metadata": {
            "name": "sensu-influxdb-handler", 
            "namespace": "default"
        }
    }
}
```

and when i go to my sensu instance, this is what i get:
```
$ sensuctl asset info sensu-influxdb-handler
=== sensu-influxdb-handler
Name:             sensu-influxdb-handler
Namespace:        default
URL:              
SHA-512 Checksum: 
Filters:          
```
all the parameters are empty.

when i tried to manually(through sensuctl) create the asset the same way ansible does that,
sensu claims to not support the 'builds' field:
```
resource 0: json: unknown field "builds"
Error: some resources couldn't be parsed
```

this is the yaml i used to create the asset manually:
```
type: Asset
api_version: core/v2
metadata:
  name: sensu-influxdb-handler
  namespace: default
spec:
  builds:
  - sha512: 612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd
    url: https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz
```

**How to reproduce the bug**
1. Run ansible playbook with the following yaml:
```
- name: manage influxdb asset
      asset:
        auth:
          url: https://localhost:8080
          password: '{{ sensu_password }}'
        namespace: default
        state: present
        name: sensu-influxdb-handler
        builds:
          - url: https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz
            sha512: 612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd
      vars:
        sensu_password: SENSU_ENCRYPTED_PASSWORD
```
2. look at the assets that were created... 

**Expected result**
i would expect a valid asset to be created

**Actual result**
invalid asset is created with empty fields.

**Component versions**
 - Ansible Version 2.9.1
 - Sensu Go Collection Version: 1.0.0
 - Sensu Go Backend Version sensu-go-backend-5.14.0-6578.x86_64

**Comment by Alexc0007** [comment]
just tested asset creation on the latest sensu version sensu-go-backend-5.16.1-8521.x86_64
and its the same behavior

**Comment by tadeboro** [comment]
I cannot replicate that behavior. These are the steps I took while verifying the report. First, I created this simple playbook:

```
---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: manage influxdb asset
      sensu.sensu_go.asset:
        name: sensu-influxdb-handler
        builds:
          - url: https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz
            sha512: 612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd
```

Then I started a fresh instance of Sensu Go backend service:

```
$ docker run -p 8080:8080 sensu/sensu:5.16.1 sensu-backend start --log-level debug
waiting for backend to become available before running backend-init...
{"component":"etcd","level":"info","msg":"listening for peers on ","pkg":"embed","time":"2019-12-19T07:53:16Z"}
{"component":"etcd","level":"info","msg":"http://127.0.0.1:2380","pkg":"embed","time":"2019-12-19T07:53:16Z"}
{"component":"etcd","level":"info","msg":"listening for client requests on ","pkg":"embed","time":"2019-12-19T07:53:16Z"}
# More output here
```

In another terminal, I ran the playbook:

```
$ ansible-playbook -vvv play.yaml 
ansible-playbook 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tadej/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: play.yaml ***************************************************************************************************************************************************************************************************************************
1 plays in play.yaml

PLAY [localhost] ******************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [manage influxdb asset] ******************************************************************************************************************************************************************************************************************
task path: /home/tadej/xlab/sensu/cli-5.16.0/play.yaml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tadej
<127.0.0.1> EXEC /bin/sh -c 'echo ~tadej && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255 `" && echo ansible-tmp-1576742051.768345-180582687292255="` echo /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255 `" ) && sleep 0'
Using module file /home/tadej/.ansible/collections/ansible_collections/sensu/sensu_go/plugins/modules/asset.py
<127.0.0.1> PUT /home/tadej/.ansible/tmp/ansible-local-2865371jyocou7z/tmph9gf8ou1 TO /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255/AnsiballZ_asset.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255/ /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255/AnsiballZ_asset.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255/AnsiballZ_asset.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/tadej/.ansible/tmp/ansible-tmp-1576742051.768345-180582687292255/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "annotations": {},
            "auth": {
                "password": "P@ssw0rd!",
                "url": "http://localhost:8080",
                "user": "admin"
            },
            "builds": [
                {
                    "filters": null,
                    "headers": null,
                    "sha512": "612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd",
                    "url": "https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz"
                }
            ],
            "labels": {},
            "name": "sensu-influxdb-handler",
            "namespace": "default",
            "state": "present"
        }
    },
    "object": {
        "builds": [
            {
                "filters": null,
                "headers": null,
                "sha512": "612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd",
                "url": "https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz"
            }
        ],
        "filters": null,
        "headers": null,
        "metadata": {
            "name": "sensu-influxdb-handler",
            "namespace": "default"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

During the play execution, the backend logged this:

```
{"component":"apid","duration":"0.287ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default/assets/sensu-influxdb-handler","size":32,"status":404,"time":"2019-12-19T07:54:12Z"}
{"component":"apid","duration":"0.460ms","level":"info","method":"PUT","msg":"request completed","path":"/api/core/v2/namespaces/default/assets/sensu-influxdb-handler","size":0,"status":201,"time":"2019-12-19T07:54:12Z"}
{"component":"apid","duration":"0.999ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default/assets/sensu-influxdb-handler","size":409,"status":200,"time":"2019-12-19T07:54:12Z"}
```

And running info command on created asset produced this:

```
$ ./sensuctl asset info sensu-influxdb-handler
=== sensu-influxdb-handler
Name:             sensu-influxdb-handler
Namespace:        default
Builds:           
Build:            0
URL:              https://github.com/sensu/sensu-influxdb-handler/releases/download/3.1.2/sensu-influxdb-handler_3.1.2_linux_amd64.tar.gz
SHA-512 Checksum: 612c6ff9928841090c4d23bf20aaf7558e4eed8977a848cf9e2899bb13a13e7540bac2b63e324f39d9b1257bb479676bc155b24e21bf93c722b812b0f15cb3bd
Filters:
```

And backend logged this during the info call:

```
{"component":"apid","duration":"0.340ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default/assets/sensu-influxdb-handler","size":409,"status":200,"time":"2019-12-19T07:54:26Z"}
```

Not sure where things went haywire on your setup, but maybe backend logs can be of some help here?
