### ISSUE TITLE
objc[3764]: +[__NSCFConstantString initialize] when installing bonsai asset

### ISSUE THREAD

**Issue by paulpet** [sensu/sensu-go-ansible#133]
**Bug description**
Calling the 'bonsai_asset' module errors out with when running Ansible from macOS 10.15.2:

**How to reproduce the bug**
1. Create Ansible playbook.yml:
```
---
- hosts: sensuservers
  collections: [ sensu.sensu_go ]
  environment:
    SENSU_URL: http://sensuserver:8080
    SENSU_USER: admin
    SENSU_PASSWORD: password

  tasks:
    - name: Create prod namespace
      namespace:
        name: prod
        state: present

    - name: Ruby runtime asset
      bonsai_asset:
        name: sensu/sensu-ruby-runtime
        version: 0.0.10
```

2. Execute `ansible-playbook --vault-password-file ~/.vault -i hosts/sensuservers playbook.yml`

**Expected result**
Install Bonsai asset

**Actual result**
```
PLAY [sensuservers] ***********************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [sensuserver]

TASK [Create prod namespace] ***************************************************************************
changed: [sensuserver]

TASK [Ruby runtime asset] ******************************************************************************
objc[4083]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[4083]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

**Component versions**
 - macOS 10.15.2 (Catalina)
 - Ansible Version 2.9.2 (python v3.7.6)
 - Sensu Go Backend Version 5.16.1
