### ISSUE TITLE
Bonsai Plugin Broken in 1.1.0

### ISSUE THREAD

**Issue by TheMaskMaker** [sensu/sensu-go-ansible#134]
**Bug description**
attempting to use the bonsai asset plugin as per the example:

 ```
- name: Make sure specific version of asset is installed
  bonsai_asset:
    name: sensu/monitoring-plugins
    version: 2.2.0-1
```

yields:

```
  "changed": false,
    "msg": "name should be <type 'str'>",
    "warning": [
        "ActionModule.run() no longer honors the tmp parameter. Action plugins should set self._connection._shell.tmpdir to share the tmpdir"
    ]
```

**Component versions**
 - Ansible Version [e.g. 2.9.0]
 - Sensu Go Collection Version [e.g. 1.1.0]
 - Sensu Go Backend Version [e.g. 5.16.0]
