### ISSUE TITLE
Documentation for namespace syntax appears to be wrong

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go-ansible#172]
**Bug description**
Documentation here for namespaces:

https://github.com/sensu/sensu-go-ansible/blob/master/plugins/modules/namespace.py#L38-L48

shows a `namespace` parameter. However, when attempting to use an example like that, this error happens:

```
Unsupported parameters for (sensu.sensu_go.namespace) module: namespace Supported parameters include: auth, name, state
```

**How to reproduce the bug**
1. Use the documentation example to try and add a namespace.
2. See resulting error that `namespace` is not a valid parameter.

**Expected result**
Documentation has valid examples.

**Actual result**
See description above.

**Component versions**
 - Ansible Version 2.9.0
 - Sensu Go Collection Version 1.2.0
 - Sensu Go Backend Version 5.19 (pre-release).

**Additional context**

**Comment by rgeniesse** [comment]
hm, actually I think this might be just user error. Other resource examples have that and I call these modules in a different way than is documented. I'll re-open if that isn't true.

**Comment by tadeboro** [comment]
We changed the API of the modules just before the 1.0.0 release of the collection. Before the change, the namespace parameter was nested inside the auth parameter. But that made the modules awkward to use if one wanted to manipulate resources from different namespaces, so we promoted it to the top-level parameter. Another reason why we moved the namespace out of the auth parameter is that some resources are not namespaced.

So, this is how tasks used to look before 1.0.0:

```
- name: Create an asset
  sensu.sensu_go.asset:
    name: my-asset
    auth:
      url: http://127.0.0.1:8080
      user: user
      password: pass
      namespace: my-namespace
    # more params here
```

And this is how the same task looks now:

```
- name: Create an asset
  sensu.sensu_go.asset:
    name: my-asset
    namespace: my-namespace
    auth:
      url: http://127.0.0.1:8080
      user: user
      password: pass
    # more params here
```

I guess you have some playbooks that were written for the pre-1.0.0 version of the collection.

The documentation about the general API design is available [here](https://sensu.github.io/sensu-go-ansible/modules.html).
