### ISSUE TITLE
`user` resource is not idempotent

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go-ansible#183]
**Bug description**

the resource always returns `changed=true`.

**How to reproduce the bug**

1. Create a user with the resource in a playbook
1. Run the playbook again

**Expected result**

If the resource attributes are same, it returns `changed=false`.

**Actual result**

the resource returns `changed=true`.

**Component versions**
 - Ansible Version 2.9.7
 - Sensu Go Collection Version 1.3.1
 - Sensu Go Backend Version 5.19.1

**Additional context**

this prevents tests with `test-kitchen` from pass.

**Comment by tadeboro** [comment]
This bug has already been reported in #175 and resolved in #180. If you want to manage Sensu Go 5.19, you will need to install version 1.4.0 of sensu.sensu_go Ansible Collection.

You can update your installed collection by running `ansible-galaxy collection install -f sensu.sensu_go`. If you leave out the `-f` switch, `ansible-galaxy` will not update the existing installation.

**Comment by trombik** [comment]
are you sure it's been fixed? the resource in 1.4.0 still says its changed in the second run in my test.

```yaml
---
collections:
  - name: sensu.sensu_go
    src: https://github.com/sensu/sensu-go-ansible
    version: 1.4.0
```

also, it looks to me that [the test](https://github.com/sensu/sensu-go-ansible/blob/master/tests/integration/molecule/module_user/converge.yml) does not cover the case.

**Comment by trombik** [comment]
here is the test-kitchen log from the second run:

```
       TASK [ansible-role-sensu_go_backend : Configure sensu_go_backend_users] ********
       changed: [localhost] => (item={'user': {'name': 'readonly-user', 'password': 'PassWord', 'groups': []}}) => changed=true 
         ansible_loop_var: item
         item:
           user:
             groups: []
             name: readonly-user
             password: PassWord
         object:
           disabled: false
           username: readonly-user
```
