### ISSUE TITLE
ability to install assets by name

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go-ansible#184]
**Is your feature request related to a problem? Please describe.**

the current implementation requires `builds` as dict of url, sha512, etc of every platform/arch/version matrix. it is impractical when you can do the same thing by `sensuctl asset add sensu-plugins/sensu-plugins-http:6.0.0`.

**Describe the solution you'd like**

i would like to remove `builds`, and simply specify name only, possibly with version.

```yaml
- name Install sensu-plugins/sensu-plugins-http asset
  sensu.sensu_go.asset:
    name: sensu-plugins/sensu-plugins-http
    version: 6.0.0
    state: present
```
download the yaml, parse it, generate `builds` from it, post the result to API endpoint. this is the same logic found in https://github.com/sensu/sensu-go/blob/master/cli/commands/asset/add.go

if the module accepts URL as well, that would be great.

```yaml
- name Install sensu-plugins/sensu-plugins-http asset
  sensu.sensu_go.asset:
    name: https://github.com/foo/bar
    version: master
    state: present
```

this would be very useful when you are testing/debugging an asset.

**Describe alternatives you've considered**

I can do it by wrapping `sensu.sensu_go.asset` in my own implementation using various tasks.

**Additional context**

n/a
