### ISSUE TITLE
check_hooks in check module does not explain what the dict is

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go-ansible#189]
**Bug description**

`check` module has `check_hooks` attribute but the documentation only states that "A mapping of response codes to hooks which will be run by the agent when that code is returned". it states the type is `dict`, but it does not explain what dict should be passed.

[check-hooks](https://docs.sensu.io/sensu-go/latest/reference/checks/#check-hooks) in the official documentation is also confising because it is an array, and does not explain much either.

**How to reproduce the bug**

n/a

**Expected result**

the doc explains what the dict is.

**Actual result**

the doc does not explain anything with the dict.

**Component versions**
 - Ansible Version [e.g. 2.9.0] n/a
 - Sensu Go Collection Version [e.g. 0.7.5] n/a
 - Sensu Go Backend Version [e.g. 5.14.1] n/a

**Additional context**

n/a

**Comment by trombik** [comment]
for the record, this worked for me.

```yaml
      name: check_http
      command: '{% raw %}{{ .labels.nagios_plugin_dir }}/check_http{% endraw %} -H {% raw %}{{ index .labels "nginx_hostname" }}{% endraw %}'
      output_metric_format: nagios_perfdata
      interval: 60
      publish: true
      subscriptions:
        - web_server
      state: present
      handlers:
        - slack
      check_hooks:
        critical:
          - process_tree
```

the dict should have keys of statuses, and their values should be a list of name of hooks.
