### ISSUE TITLE
modules do not support TLS

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go-ansible#190]
**Bug description**

many modules, if not all, do not support TLS. they lacks attributes to define path to CA root certificate.

**How to reproduce the bug**

1. enable TLS in backend
1. run any modules with https url, for example:

```yaml
sensu.sensu_go.namespace:
  auth:
    url: https://127.0.0.1:8080
```

the play fails with a message:

```
msg: 'GET request failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)'
```

**If applicable, content of the files used in commands from the previous step**
For example, `inv` file from previous sample could contain:

n/a

**Expected result**

the module support TLS.

**Actual result**

it fails to verify the backend.

**Component versions**
 - Ansible Version [e.g. 2.9.0] 2.9.7
 - Sensu Go Collection Version [e.g. 0.7.5] the latest
 - Sensu Go Backend Version [e.g. 5.14.1] 5.20.0

**Additional context**

to me, it looks like no module supports TLS. cannot find any TLS-related code, such as disable verification, or set path to certificates.

also, it looks like you need to set `auth` in every single module invocation because the url is not default. how can I set common configuration parameters, like `url` in one place? looks impossible. there are some tests for TLS-enabled etcd and backend, but not modules.

**Comment by trombik** [comment]
in practice, i can workaround the issue by using HTTP on localhost because the module is invoked on the backend host. but there would be cases where you cannot.

**Comment by tadeboro** [comment]
@trombik We just merged a PR #204 that allows playbook authors to disable the certificate verification completely or to use a custom CA bundle for verification.

You can now connect to the backend that uses a self-signed certificate in one of the following ways:

```
- name: List assets without validating certificate at all
  sensu.sensu_go.asset_info:
    auth:
      url: https://backend.address:8080
      verify: false
```

```
- name: List assets using custom CA bundle for cert verification
  sensu.sensu_go.asset_info:
    auth:
      url: https://backend.address:8080
      ca_path: /path/to/ca.bundle
```

Note that authentication parameters can also be set using the environment variables. This makes it possible to defined credentials in a single place and then use them in all tasks. Environment variables can be set in the playbook directly or in the shell that `ansible-playbook` has been run from:

```
# Run playbook using:
#   $ ansible-playbook playbook.yaml

- name: Sample playbook with vars
  hosts: localhost
  gather_facts: false

  environment:
    SENSU_URL: https://backend.address:8080
    SENSU_USER: my-user
    SENSU_PASSWORD: my-password
    SENSU_CA_PATH: /path/to/ca.bundle

  tasks:
    - name: Task 1
      sensu.sensu_go.asset:
        # No auth parameter needed here
        name: my-asset
        # More parameters here

    - name: Task 2
      sensu.sensu_go.mutator:
        # No auth parameter needed here
        name: my-mutator
        # More parameters here

    - name: Task 3
      sensu.sensu_go.check:
        # No auth parameter needed here
        name: my-check
        # More parameters here
```

```
# Run playbook using:
#   $ SENSU_URL='https://backend.address:8080' \
#     SENSU_USER='my-user' \
#     SENSU_PASSWORD='my-password' \
#     SENSU_CA_PATH='/path/to/ca.bundle' \
#     ansible-playbook playbook.yaml

- name: Sample playbook with vars
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Task 1
      sensu.sensu_go.asset:
        # No auth parameter needed here
        name: my-asset
        # More parameters here

    - name: Task 2
      sensu.sensu_go.mutator:
        # No auth parameter needed here
        name: my-mutator
        # More parameters here

    - name: Task 3
      sensu.sensu_go.check:
        # No auth parameter needed here
        name: my-check
        # More parameters here
```

Happy automating!
