### ISSUE TITLE
bonsai_asset plugin - GET request failed: timed out

### ISSUE THREAD

**Issue by michaeldeaton** [sensu/sensu-go-ansible#311]
**Bug description**
Using the latest version of the collection - trying to install bonsai assets fails with the error:
````
{
  "msg": "GET request failed: timed out",
  "_ansible_no_log": false,
  "changed": false,
  "item": {
    "name": "sensu-plugins/sensu-plugins-memory-checks",
    "version": "4.1.1"
  },
  "ansible_loop_var": "item",
  "_ansible_item_label": {
    "name": "sensu-plugins/sensu-plugins-memory-checks",
    "version": "4.1.1"
  }
````

**How to reproduce the bug**
Playbook:

````
    - name: install bonsai assets for pap
      bonsai_asset:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        annotations: "{{ item.annotations| default(omit) }}"
        filters: "{{ item.filters | default(omit) }}"
        namespace: "pap"
        rename: "{{ item.rename | default(omit) }}"
      loop: "{{ sensu_bonsai_assets }}"
      tags: sensu_backend_config, sensu_backend_assets
````

vars:
````
  sensu_bonsai_assets:
    - name: sensu-plugins/sensu-plugins-memory-checks
      version: 4.1.1
    - name: sensu-plugins/sensu-plugins-load-checks
      version: 5.1.0
    - name: sensu-plugins/sensu-plugins-cpu-checks
      version: 4.1.0
````

**Expected result**
For the asset to be installed

**Actual result**
failure as per above error.

**Component versions**
 - Ansible Version 2.9.0
 - Sensu Go Collection Version 1.12.1
 - Sensu Go Backend Version 6.6.3

**Additional context**
I'm in an environment where internet access is severely limited - however i am able to install bonsai assets with sensuctl - i don't suppose the ansible controller is doing the downloading and that's where it's failing? none of my tasks are set to delegate to localhost and should run on the target machine (the sensu backend machine).

Thanks

michael
