### ISSUE TITLE
Unable to use the namespace metadata attribute.

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go-ansible#92]
In using `assets`, I would like to have them created in multiple namespaces. As resources like `assets` can only live in one namespace, this requires specifying the namespace in the resource definition.

Looking here:

https://github.com/sensu/sensu-go-ansible/blob/master/plugins/modules/asset.py#L102

It would seem as though they are not supported. I searched the repo for mentions of namespace and didn't see anywhere else that it would come into play, however I only know Python enough to get me into trouble.

This is further supported by an error when `namespace` is used in an asset module:

```
"msg": "Unsupported parameters for (sensu.sensu_go.asset) module: namespace Supported parameters include: annotations, auth, filters, headers, labels, name, sha512, state, url"}
```

As `namespaces` are a supported module in this collection, users wouldn't actually be able to use anything else except for `default`. I also found that other modules, such as checks, also appear to not support them.

A list of namespaced resources can be found here:

https://docs.sensu.io/sensu-go/5.14/reference/rbac/#namespaced-resource-types

Example:

```
    - name: Create test asset for namespace default
      sensu.sensu_go.asset:
        name: sensu-test
        url: http://www.example.com
        sha512: c9f0aff8f7f
        namespace: default
```
