### ISSUE TITLE
Unable to create UDP handler using sensu_go_handler

### ISSUE THREAD

**Issue by mkobel** [sensu/sensu-go-ansible#98]
I'm unable to create a UDP handler using `sensu_go_handler`:

Playbook:

```yaml
    - name: create sensu core gateway handler
      sensu_go_handler:
        auth: "{{ sensu_auth }}"
        name: sensu-core-gateway
        type: udp
        socket_host: localhost
        socket_port: "{{ 4446 | int }}"
        filters:
          - sensu-go-only
```

Error:

```
TASK [create sensu core gateway handler] ***************************************************************************************************************************************************************************************************************************************************
fatal: [******]: FAILED! => {"changed": false, "msg": "put failed: Bad Request {\"message\":\"json: cannot unmarshal string into Go struct field HandlerSocket.socket.port of type uint32\",\"code\":1}"}
```

Environment:

* ansible: 2.9.0
* sensu.sensu_go: 0.7.8
* sensu go: 5.14.2-7022 

Without typecast of the port number I get the same error and the additional warning: `The value 4446 (type int) in a string field was converted to u'4446' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.`
